name: 'Draft Release Notify'
description: 'Draft Release Notify'
inputs:
  slack-api-token:
    description: 'API token for Slack'
    required: true
  channel:
    description: "Channel to send message"
    required: true
  mention-person:
    description: "User to mention in message"
runs:
  using: "composite"
  steps:
    - name: job-status
      shell: bash
      run: |
        echo "job_status=${{ job.status }}" >> $GITHUB_ENV
    - name: Notify
      uses: Basis-Theory/github-actions/helper-slack-action@eng-6358
      with:
        github: ${{ toJSON(github) }}
        slack-api-token: ${{ inputs.slack-api-token }}
        channel: ${{ inputs.channel }}
        mention-person: ${{ inputs.mention-person }}
        type: "draft-release-ready"
