name: "Slack Message"
description: "Send, update, or thread a message to Slack"
inputs:
  slack-api-token:
    description: "API token for Slack"
    required: true
  channel:
    description: "Channel to send to"
    required: true
  blocks:
    description: "Blocks to send"
  text:
    description: "Text of a message"
  update-message-id:
    description: "Update this message"
  thread-message-id:
    description: "Add message to thread of this message"
outputs:
  message_id:
    description: "Message Id of the sent message"
runs:
  using: "node16"
  main: "../slack-javascript-action/dist/slack/index.js"
